services:
  proxy:
    image: mitmproxy/mitmproxy
    command:
      - 'mitmweb'
      - '--no-web-open-browser'
      - '--listen-port'
      - '8080'
      - '--web-host'
      - '0.0.0.0'
      # - '--set'
      # - 'web_password=test'
    tty: true
    ports:
      - 8080:8080
      - 127.0.0.1:8081:8081
